### PR TITLE
Add sidetab-adapta theme

### PR DESCRIPTION
**Pull request by laferuben**
A mashup of Adapta-Nokto and sidetab themes.

### CODE REVIEW

**Comment by SpotlightKid** [comment]
I like this one, though I think it should be wider by default.

**Comment by laferuben** [comment]
It is a sidebar, it should not be wide. We can decide on the width but in absolute values please, no percents.

**Comment by SpotlightKid** [comment]
With the current width, when used in "drun" mode, lots of application names do not fit. It may have to do with the font and DPI of my display, though.

**Comment by laferuben** [comment]
Even when I use 12 size font, "GNU Image Manipulation Program" title has some space left. And 12 size on 14" screen is huge already.

**Comment by laferuben** [comment]
@DaveDavenport, somebody even see pull requests here?

**Comment by DaveDavenport** [comment]
Sorry I have been very busy.  I will accept this later today.

**Comment by DaveDavenport** [comment]
Can you put a header in the theme?
like:
```
/*
 * MyTheme name
 *
 * Based on ....
 *
 * Author: ...
 * User: ....
 *
 */
```

**Comment by laferuben** [comment]
Will do.

**Pull request closed without merging**
